# Docker Compose Override for Development
# This file is automatically loaded and provides development-specific configurations

version: '3.8'

services:
  # Development overrides for MinIO
  minio:
    # Add development volume mounts for persistent data
    volumes:
      - minio_dev_data:/data
    # Development environment variables
    environment:
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001

  # Development overrides for Visual Tests
  visual-tests:
    # Mount local files for development
    volumes:
      - .:/app
      - /app/node_modules  # Prevent overwriting container node_modules
      - ./tests/logs:/app/tests/logs
      - ./tests/reports:/app/tests/reports
      - ./test-results:/app/test-results
    # Development environment
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    # Override command for development
    command: >
      sh -c "
        echo 'Development mode: Running tests with hot reload...' &&
        npm run visual-tests:local
      "

  # Development Storybook service
  storybook-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6007:6006"  # Different port to avoid conflicts
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run storybook
    networks:
      - visual-testing-network
    profiles:
      - development

  # Development report viewer
  reports-dev:
    extends: reports
    ports:
      - "8081:80"  # Different port for development
    profiles:
      - development

volumes:
  minio_dev_data:
    driver: local